# get all indexes
GET http://localhost:9200/_cat/indices?v

# careful!
#DELETE http://localhost:9200/example

# mapping
GET http://localhost:9200/example/dataset/_mapping

# search
POST http://localhost:9200/example/dataset/_search
{
    "query": { "match_all": {}},
    "size": 1
}

# distribution
POST http://localhost:9200/example/dataset/_search
{
    "aggs": {
        "act_agg_name": {
	    "terms": {"field": "class-label", "size": 0}
        }
    },
    "size": 0
}

# act by phase
POST http://localhost:9200/example/dataset/_search
{
    "query": {
        "term": {"class-label": "answer"}
   },
   "fields": ["class-label"],
   "size": 5
}

# counts
POST http://localhost:9200/example/dataset/_search
{
    "query": { "match_all": {}},
    "size": 0
}

# just keys
POST http://localhost:9200/example/dataset/_search
{
    "query": { "match_all": {}},
    "fields": []
}

# search for text
POST http://localhost:9200/example/dataset/_search
{
    "query": {
      "match": {"_all": "pepsi major brands"}
    },
    "size": 1
}

## stats
GET http://localhost:9200/example/stats/_search
{
    "query": { "match_all": {}},
    "from": 0,
    "size": 9999
}
